version: "3.9"  # optional since v1.27.0
services:
  sd-infinity:
    build: docker
    ports:
      - "7860:7860"
    stdin_open: true
    tty: true
    command: "/home/user/app/docker/entrypoint.sh"
    environment:
      - HUGGINGFACE_TOKEN
    volumes:
      - .:/home/user/app
      - user_home:/home/user
      - cond_env:/opt/conda/envs
      - /dev/shm:/dev/shm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

volumes:
  user_home: {}
  cond_env: {}